[pytest]
asyncio_mode = auto
testpaths = ../tests tests
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning

[coverage:run]
source = app
omit = app/__init__.py

[coverage:report]
fail_under = 35
show_missing = true