FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN addgroup --system nebula && adduser --system --ingroup nebula nebula

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt
COPY backend/pytest.ini .
COPY backend/app ./app/app
COPY backend/vector ./vector
COPY backend/static ./static

RUN mkdir -p /app/storage && chown -R nebula:nebula /app

USER nebula

EXPOSE 8000/tcp

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug", "--reload"]
