{{- if .Values.vectorWorker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nebula.fullname" . }}-vector-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: nebula-vector-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: vector-worker
    app.kubernetes.io/part-of: nebula
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nebula.fullname" . }}-vector-worker
  minReplicas: {{ .Values.vectorWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.vectorWorker.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.vectorWorker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.vectorWorker.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}